export const mockCandidate = {
  profile: {
    image: "/image-2.png",
    name: "Kanishq Sodhani",
    location: "Bangalore, India",
    designation: "Frontend Developer",
    company: "Workflow",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Tailwind",
      "MongoDB",
    ],
    bio: "Frontend developer with 3+ years of experience building scalable SaaS dashboards and modern web applications using React ecosystem. Passionate about performance optimization and clean UI architecture.",
    experienceTag: "Experienced" as const,
    profileTag: "New Profile" as const,
    salary: "14–18 LPA",
    jobType: "Hybrid",
    joiningType: "Immediate",
    verified: true,
  },

  projects: [
    {
      title: "Hireance Job Portal",
      description:
        "A full stack SaaS job portal where recruiters can hire candidates and job seekers can apply to companies. Includes admin dashboard and analytics.",
      skills: ["Next.js", "TypeScript", "MongoDB", "Tailwind"],
      startDate: "Jan 2025",
      endDate: "Present",
      github: "https://github.com/example/hireance",
      live: "https://hireance.com",
    },
    {
      title: "AI Resume Analyzer",
      description:
        "AI powered resume analyzer that evaluates candidate resumes and provides improvement suggestions using OpenAI APIs.",
      skills: ["React", "Node.js", "OpenAI", "Express"],
      startDate: "Oct 2024",
      endDate: "Dec 2024",
      github: "https://github.com/example/resume-ai",
      live: "https://resume-ai.app",
    },
    {
      title: "SaaS Analytics Dashboard",
      description:
        "A modern analytics dashboard used by startups to track revenue, growth and user metrics with beautiful data visualizations.",
      skills: ["Next.js", "Recharts", "Tailwind"],
      startDate: "Jun 2024",
      endDate: "Aug 2024",
      github: "https://github.com/example/saas-dashboard",
    },
  ],

  experiences: [
    {
      companyLogo: "/logos/infosys.png",
      companyName: "Infosys",
      role: "Frontend Developer",
      joinAs: "Associate",
      location: "Bangalore, India",
      workType: "Hybrid",
      startDate: "Jan 2023",
      endDate: "Present",
      skills: ["React", "Next.js", "TypeScript"],
      description: [
        "Developed scalable UI components for enterprise SaaS dashboards",
        "Improved application performance by 35%",
        "Collaborated with backend teams for API integration",
      ],
    },
    {
      companyLogo: "/logos/amazon.png",
      companyName: "Amazon",
      role: "Frontend Intern",
      joinAs: "Intern",
      location: "Hyderabad, India",
      workType: "Office",
      startDate: "Jun 2022",
      endDate: "Dec 2022",
      skills: ["React", "Redux", "JavaScript"],
      description: [
        "Built internal HR dashboard for employee analytics",
        "Optimized UI components and reduced load time",
        "Worked closely with design team for UI improvements",
      ],
    },
  ],

  applications: [
    {
      companyLogo: "/logos/google.png",
      companyName: "Google",
      location: "Bangalore, India",
      jobType: "Hybrid",
      role: "Frontend Engineer",
      department: "Engineering",
      experienceRequired: "Associate (2-4 years)",
      salaryRange: "20–28 LPA",
      skills: ["React", "TypeScript", "Next.js"],
      joiningDate: "Aug 2025",
      appliedDate: "12 Mar 2025",
      status: "Interview" as const,
    },
    {
      companyLogo: "/logos/microsoft.png",
      companyName: "Microsoft",
      location: "Hyderabad, India",
      jobType: "Remote",
      role: "UI Developer",
      department: "Product Engineering",
      experienceRequired: "Experienced (3+ years)",
      salaryRange: "18–24 LPA",
      skills: ["React", "JavaScript", "CSS"],
      joiningDate: "July 2025",
      appliedDate: "5 Mar 2025",
      status: "Shortlisted" as const,
    },
    {
      companyLogo: "/logos/adobe.png",
      companyName: "Adobe",
      location: "Bangalore, India",
      jobType: "Hybrid",
      role: "Frontend Developer",
      department: "Creative Cloud",
      experienceRequired: "Associate",
      salaryRange: "16–22 LPA",
      skills: ["React", "TypeScript"],
      joiningDate: "Sep 2025",
      appliedDate: "18 Feb 2025",
      status: "Applied" as const,
    },
    {
      companyLogo: "/logos/flipkart.png",
      companyName: "Flipkart",
      location: "Bangalore, India",
      jobType: "Office",
      role: "UI Engineer",
      department: "Marketplace",
      experienceRequired: "Associate (2+ years)",
      salaryRange: "14–18 LPA",
      skills: ["React", "Next.js", "CSS"],
      joiningDate: "June 2025",
      appliedDate: "10 Feb 2025",
      status: "Rejected" as const,
    },
  ],
};
