export const jobSeekers = [
  {
    id: "1",
    name: "Rahul Sharma",
    image: "/profiles/p1.jpg",
    skills: ["React", "Next.js", "TypeScript"],
    company: "Infosys",
    designation: "Frontend Developer",
    location: "Bangalore",
    experience: 3,
  },
  {
    id: "2",
    name: "Priya Verma",
    image: "/profiles/p2.jpg",
    skills: ["Python", "Django"],
    company: "TCS",
    designation: "Backend Engineer",
    location: "Hyderabad",
    experience: 4,
  },
  {
    id: "3",
    name: "Amit Patel",
    image: "/profiles/p3.jpg",
    skills: ["Java", "Spring Boot", "AWS"],
    company: "Wipro",
    designation: "Software Engineer",
    location: "Pune",
    experience: 5,
  },
  {
    id: "4",
    name: "Sneha Reddy",
    image: "/profiles/p4.jpg",
    skills: ["Node.js", "Express", "MongoDB"],
    company: "Zomato",
    designation: "Backend Developer",
    location: "Gurgaon",
    experience: 2,
  },
  {
    id: "5",
    name: "Vikram Singh",
    image: "/profiles/p5.jpg",
    skills: ["Angular", "RxJS", "JavaScript"],
    company: "HCL Tech",
    designation: "UI Developer",
    location: "Noida",
    experience: 6,
  },
  {
    id: "6",
    name: "Anjali Gupta",
    image: "/profiles/p6.jpg",
    skills: ["Flutter", "Dart", "Firebase"],
    company: "Swiggy",
    designation: "Mobile App Developer",
    location: "Bangalore",
    experience: 3,
  },
  {
    id: "7",
    name: "Rohan Das",
    image: "/profiles/p7.jpg",
    skills: ["Go", "Kubernetes", "Docker"],
    company: "Google",
    designation: "DevOps Engineer",
    location: "Hyderabad",
    experience: 4,
  },
  {
    id: "8",
    name: "Megha Iyer",
    image: "/profiles/p8.jpg",
    skills: ["PHP", "Laravel", "MySQL"],
    company: "Cognizant",
    designation: "Full Stack Developer",
    location: "Chennai",
    experience: 5,
  },
  {
    id: "9",
    name: "Arjun Mehta",
    image: "/profiles/p9.jpg",
    skills: ["C#", ".NET Core", "Azure"],
    company: "Microsoft",
    designation: "Cloud Engineer",
    location: "Bangalore",
    experience: 7,
  },
  {
    id: "10",
    name: "Kavita Rao",
    image: "/profiles/p10.jpg",
    skills: ["Swift", "iOS SDK", "Xcode"],
    company: "Cred",
    designation: "iOS Developer",
    location: "Mumbai",
    experience: 4,
  },
  {
    id: "11",
    name: "Suresh Menon",
    image: "/profiles/p11.jpg",
    skills: ["Rust", "C++", "Embedded Systems"],
    company: "Bosch",
    designation: "Systems Engineer",
    location: "Coimbatore",
    experience: 8,
  },
  {
    id: "12",
    name: "Ishita Bose",
    image: "/profiles/p12.jpg",
    skills: ["Data Science", "R", "Tableau"],
    company: "Deloitte",
    designation: "Data Analyst",
    location: "Kolkata",
    experience: 2,
  },
  {
    id: "13",
    name: "Manish Joshi",
    image: "/profiles/p13.jpg",
    skills: ["Vue.js", "Nuxt.js", "Tailwind"],
    company: "Razorpay",
    designation: "Frontend Engineer",
    location: "Bangalore",
    experience: 3,
  },
  {
    id: "14",
    name: "Pooja Hegde",
    image: "/profiles/p14.jpg",
    skills: ["GraphQL", "Apollo", "React"],
    company: "Postman",
    designation: "Software Engineer II",
    location: "Remote",
    experience: 4,
  },
  {
    id: "15",
    name: "Abhishek Nair",
    image: "/profiles/p15.jpg",
    skills: ["Blockchain", "Solidity", "Ether.js"],
    company: "Polygon",
    designation: "Web3 Developer",
    location: "Dubai",
    experience: 3,
  },
  {
    id: "16",
    name: "Tanvi Shah",
    image: "/profiles/p16.jpg",
    skills: ["UI/UX Design", "Figma", "Adobe XD"],
    company: "Flipkart",
    designation: "Product Designer",
    location: "Bangalore",
    experience: 5,
  },
  {
    id: "17",
    name: "Karan Malhotra",
    image: "/profiles/p17.jpg",
    skills: ["Machine Learning", "PyTorch", "NLP"],
    company: "Amazon",
    designation: "ML Engineer",
    location: "Hyderabad",
    experience: 4,
  },
  {
    id: "18",
    name: "Deepika Pillai",
    image: "/profiles/p18.jpg",
    skills: ["QA Automation", "Selenium", "Cypress"],
    company: "Paytm",
    designation: "SDET",
    location: "Noida",
    experience: 6,
  },
  {
    id: "19",
    name: "Varun Dhawan",
    image: "/profiles/p19.jpg",
    skills: ["Ruby on Rails", "PostgreSQL"],
    company: "Shopify",
    designation: "Backend Developer",
    location: "Remote",
    experience: 5,
  },
  {
    id: "20",
    name: "Sanya Mirza",
    image: "/profiles/p20.jpg",
    skills: ["Kotlin", "Android SDK", "Jetpack Compose"],
    company: "Samsung",
    designation: "Android Developer",
    location: "Bangalore",
    experience: 3,
  },
  {
    id: "21",
    name: "Rahul Dravid",
    image: "/profiles/p21.jpg",
    skills: ["React Native", "Expo", "Redux"],
    company: "Uber",
    designation: "Mobile Lead",
    location: "Bangalore",
    experience: 9,
  },
  {
    id: "22",
    name: "Nisha Rawat",
    image: "/profiles/p22.jpg",
    skills: ["Salesforce", "Apex", "LWC"],
    company: "Accenture",
    designation: "CRM Consultant",
    location: "Pune",
    experience: 4,
  },
  {
    id: "23",
    name: "Aditya Roy",
    image: "/profiles/p23.jpg",
    skills: ["Scala", "Apache Spark", "Hadoop"],
    company: "J.P. Morgan",
    designation: "Big Data Engineer",
    location: "Mumbai",
    experience: 7,
  },
  {
    id: "24",
    name: "Shreya Ghoshal",
    image: "/profiles/p24.jpg",
    skills: ["SEO", "Content Strategy", "GA4"],
    company: "Byju's",
    designation: "Growth Marketer",
    location: "Bangalore",
    experience: 3,
  },
  {
    id: "25",
    name: "Zayn Malik",
    image: "/profiles/p25.jpg",
    skills: ["Cyber Security", "Penetration Testing"],
    company: "Cisco",
    designation: "Security Analyst",
    location: "Chennai",
    experience: 5,
  },
  {
    id: "26",
    name: "Preeti Zinta",
    image: "/profiles/p26.jpg",
    skills: ["PowerBI", "SQL", "Excel"],
    company: "KPMG",
    designation: "Business Analyst",
    location: "Gurgaon",
    experience: 4,
  },
  {
    id: "27",
    name: "Hrithik Roshan",
    image: "/profiles/p27.jpg",
    skills: ["Unity", "C#", "Blender"],
    company: "Dream11",
    designation: "Game Developer",
    location: "Mumbai",
    experience: 6,
  },
  {
    id: "28",
    name: "Kiara Advani",
    image: "/profiles/p28.jpg",
    skills: ["Project Management", "Jira", "Agile"],
    company: "Oracle",
    designation: "Project Manager",
    location: "Hyderabad",
    experience: 8,
  },
  {
    id: "29",
    name: "Ranbir Kapoor",
    image: "/profiles/p29.jpg",
    skills: ["Erlang", "Elixir", "Phoenix"],
    company: "WhatsApp",
    designation: "Distributed Systems Engineer",
    location: "Remote",
    experience: 5,
  },
  {
    id: "30",
    name: "Alia Bhatt",
    image: "/profiles/p30.jpg",
    skills: ["Svelte", "Vite", "CSS"],
    company: "Freshworks",
    designation: "Frontend Dev",
    location: "Chennai",
    experience: 2,
  },
];
