/* -------------------------------------------------------
   MOCK JOBS DATA
------------------------------------------------------- */

export const MOCK_JOBS = [
  { jobId: "job-1000", companyName: "Hireance", jobTitle: "Senior Frontend Engineer", exp: "3-5", location: "Remote", status: "Open", jobType: "Full-time", applications: 145, shortlisted: 12, postedOn: "2 days ago", lastActivity: "1 hr ago" },
  { jobId: "job-1001", companyName: "Hireance", jobTitle: "DevOps Specialist", exp: "5-8", location: "Jaipur, India", status: "Open", jobType: "Full-time", applications: 89, shortlisted: 8, postedOn: "4 days ago", lastActivity: "3 hrs ago" },
  { jobId: "job-1002", companyName: "Hireance", jobTitle: "FullStack AI Engineer", exp: "1-3", location: "Bangalore, India", status: "Open", jobType: "Contract", applications: 210, shortlisted: 15, postedOn: "1 day ago", lastActivity: "30 mins ago" },
  { jobId: "job-1003", companyName: "Hireance", jobTitle: "Machine Learning Trainer", exp: "5-8", location: "Remote", status: "Draft", jobType: "Part-time", applications: 0, shortlisted: 0, postedOn: "Just now", lastActivity: "Just now" },
  { jobId: "job-1004", companyName: "Hireance", jobTitle: "Backend Developer", exp: "3-5", location: "New York, USA", status: "Open", jobType: "Full-time", applications: 167, shortlisted: 22, postedOn: "6 days ago", lastActivity: "5 hrs ago" },
  { jobId: "job-1005", companyName: "Hireance", jobTitle: "Product Manager", exp: "8+", location: "London, UK", status: "Closed", jobType: "Full-time", applications: 342, shortlisted: 45, postedOn: "14 days ago", lastActivity: "2 days ago" },
  { jobId: "job-1006", companyName: "Hireance", jobTitle: "UI/UX Designer", exp: "1-3", location: "Remote", status: "Open", jobType: "Contract", applications: 94, shortlisted: 6, postedOn: "3 days ago", lastActivity: "4 hrs ago" },
  { jobId: "job-1007", companyName: "Hireance", jobTitle: "Data Scientist", exp: "3-5", location: "Bangalore, India", status: "Open", jobType: "Full-time", applications: 123, shortlisted: 18, postedOn: "5 days ago", lastActivity: "6 hrs ago" },
  { jobId: "job-1008", companyName: "Hireance", jobTitle: "Mobile Developer", exp: "2-4", location: "San Francisco, USA", status: "Open", jobType: "Full-time", applications: 78, shortlisted: 9, postedOn: "7 days ago", lastActivity: "1 day ago" },
  { jobId: "job-1009", companyName: "Hireance", jobTitle: "Cloud Architect", exp: "10+", location: "Remote", status: "Open", jobType: "Full-time", applications: 45, shortlisted: 12, postedOn: "10 days ago", lastActivity: "4 hrs ago" },
  { jobId: "job-1010", companyName: "Hireance", jobTitle: "QA Engineer", exp: "2-5", location: "Jaipur, India", status: "Open", jobType: "Full-time", applications: 112, shortlisted: 14, postedOn: "9 days ago", lastActivity: "8 hrs ago" },
  { jobId: "job-1011", companyName: "Hireance", jobTitle: "Cybersecurity Analyst", exp: "3-6", location: "London, UK", status: "Open", jobType: "Full-time", applications: 67, shortlisted: 5, postedOn: "12 days ago", lastActivity: "2 hrs ago" },
  { jobId: "job-1012", companyName: "Hireance", jobTitle: "Marketing Lead", exp: "5-7", location: "Remote", status: "Open", jobType: "Full-time", applications: 156, shortlisted: 20, postedOn: "1 day ago", lastActivity: "1 hr ago" },
  { jobId: "job-1013", companyName: "Hireance", jobTitle: "Technical Writer", exp: "2-4", location: "Bangalore, India", status: "Open", jobType: "Contract", applications: 34, shortlisted: 3, postedOn: "15 days ago", lastActivity: "3 days ago" },
  { jobId: "job-1014", companyName: "Hireance", jobTitle: "Customer Success", exp: "1-3", location: "Remote", status: "Open", jobType: "Full-time", applications: 203, shortlisted: 15, postedOn: "2 days ago", lastActivity: "6 hrs ago" },
  { jobId: "job-1015", companyName: "Hireance", jobTitle: "Data Engineer", exp: "4-7", location: "New York, USA", status: "Open", jobType: "Full-time", applications: 82, shortlisted: 11, postedOn: "4 days ago", lastActivity: "5 hrs ago" },
  { jobId: "job-1016", companyName: "Hireance", jobTitle: "Frontend Intern", exp: "0-1", location: "Remote", status: "Open", jobType: "Full-time", applications: 540, shortlisted: 30, postedOn: "3 days ago", lastActivity: "1 hr ago" },
  { jobId: "job-1017", companyName: "Hireance", jobTitle: "HR Generalist", exp: "3-5", location: "Jaipur, India", status: "Open", jobType: "Full-time", applications: 76, shortlisted: 8, postedOn: "11 days ago", lastActivity: "1 day ago" },
  { jobId: "job-1018", companyName: "Hireance", jobTitle: "iOS Developer", exp: "4-6", location: "London, UK", status: "Open", jobType: "Full-time", applications: 43, shortlisted: 6, postedOn: "13 days ago", lastActivity: "4 hrs ago" },
  { jobId: "job-1019", companyName: "Hireance", jobTitle: "Android Developer", exp: "4-6", location: "Bangalore, India", status: "Open", jobType: "Full-time", applications: 51, shortlisted: 7, postedOn: "14 days ago", lastActivity: "5 hrs ago" },
  { jobId: "job-1020", companyName: "Hireance", jobTitle: "Business Analyst", exp: "3-5", location: "Remote", status: "Open", jobType: "Full-time", applications: 122, shortlisted: 15, postedOn: "5 days ago", lastActivity: "2 hrs ago" },
  { jobId: "job-1021", companyName: "Hireance", jobTitle: "System Admin", exp: "5-8", location: "New York, USA", status: "Closed", jobType: "Full-time", applications: 65, shortlisted: 9, postedOn: "20 days ago", lastActivity: "1 week ago" },
  { jobId: "job-1022", companyName: "Hireance", jobTitle: "Growth Hacker", exp: "2-5", location: "Remote", status: "Open", jobType: "Contract", applications: 187, shortlisted: 24, postedOn: "6 days ago", lastActivity: "3 hrs ago" },
  { jobId: "job-1023", companyName: "Hireance", jobTitle: "Unity Developer", exp: "3-6", location: "Bangalore, India", status: "Open", jobType: "Full-time", applications: 29, shortlisted: 4, postedOn: "21 days ago", lastActivity: "2 days ago" },
  { jobId: "job-1024", companyName: "Hireance", jobTitle: "Python Developer", exp: "2-5", location: "Remote", status: "Open", jobType: "Full-time", applications: 312, shortlisted: 35, postedOn: "2 days ago", lastActivity: "30 mins ago" },
  { jobId: "job-1025", companyName: "Hireance", jobTitle: "Legal Counsel", exp: "7+", location: "London, UK", status: "Open", jobType: "Full-time", applications: 18, shortlisted: 3, postedOn: "25 days ago", lastActivity: "1 day ago" }
];

/* -------------------------------------------------------
   MOCK APPLICANTS DATA
------------------------------------------------------- */

export const MOCK_APPLICANTS = [
  { applicantId: "app-2000", profilePicture: "https://media.istockphoto.com/id/2203067311/photo/young-female-teacher-with-curly-hair-in-classroom-smiling-at-camera-with-arms-crossed.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWdN0e5FstxltxR6bWZ2y0BGH3hAmRb8iMYU-S9Q6uM=", applicantFullName: "Sarah Johnson", currentJobPosition: "Senior Frontend Developer", currentOrganization: "Google", location: "San Francisco, USA", experience: 5, skills: ["React", "TypeScript", "GraphQL", "Redux"], salaryRange: "15 - 20", lastUpdate: 1, linkedIn: "https://linkedin.com/in/sarah", github: "https://github.com/sarah", twitter: "https://twitter.com/sarah", gmail: "sarah@example.com", status: "Shortlisted", matchScore: 94 },
  { applicantId: "app-2001", profilePicture: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRlYWNoZXJ8ZW58MHx8MHx8fDA%3D", applicantFullName: "Raj Kumar", currentJobPosition: "Backend Engineer", currentOrganization: "Amazon", location: "Bangalore, India", experience: 4, skills: ["Node.js", "Python", "AWS", "MongoDB"], salaryRange: "12 - 18", lastUpdate: 2, linkedIn: "https://linkedin.com/in/raj", github: "https://github.com/raj", twitter: "https://twitter.com/raj", gmail: "raj@example.com", status: "Interviewed", matchScore: 88 },
  { applicantId: "app-2002", profilePicture: "https://images.unsplash.com/photo-1590650213165-c1fef80648c4?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRlYWNoZXJ8ZW58MHx8MHx8fDA%3D", applicantFullName: "Emily Chen", currentJobPosition: "DevOps Engineer", currentOrganization: "Microsoft", location: "Seattle, USA", experience: 6, skills: ["Kubernetes", "Terraform", "Jenkins", "Azure"], salaryRange: "18 - 25", lastUpdate: 3, linkedIn: "https://linkedin.com/in/emily", github: "https://github.com/emily", twitter: "https://twitter.com/emily", gmail: "emily@example.com", status: "New", matchScore: 91 },
  { applicantId: "app-2003", profilePicture: "https://plus.unsplash.com/premium_photo-1661942126259-fb08e7cce1e2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dGVhY2hlcnxlbnwwfHwwfHx8MA%3D%3D", applicantFullName: "Michael Rodriguez", currentJobPosition: "UI/UX Designer", currentOrganization: "Netflix", location: "New York, USA", experience: 3, skills: ["Figma", "Adobe XD", "Sketch", "Prototyping"], salaryRange: "10 - 15", lastUpdate: 4, linkedIn: "https://linkedin.com/in/mike", github: "https://github.com/mike", twitter: "https://twitter.com/mike", gmail: "mike@example.com", status: "Rejected", matchScore: 65 },
  { applicantId: "app-2004", profilePicture: "https://media.istockphoto.com/id/2216805149/photo/teenager-boy-carrying-bag-in-library-stock-photo.webp?a=1&b=1&s=612x612&w=0&k=20&c=Jf9esFTHuIBGfc-ppHmNVwHoK1qM9wOFsRQITX7sT9k=", applicantFullName: "John Marston", currentJobPosition: "FullStack Developer", currentOrganization: "Uber", location: "Mumbai, India", experience: 5, skills: ["Python", "Machine Learning", "TensorFlow", "SQL"], salaryRange: "14 - 19", lastUpdate: 5, linkedIn: "https://linkedin.com/in/john", github: "https://github.com/john", twitter: "https://twitter.com/john", gmail: "john@example.com", status: "New", matchScore: 82 },
  { applicantId: "app-2005", profilePicture: "https://images.unsplash.com/photo-1513258496099-48168024aec0?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHN0dWRlbnRzfGVufDB8fDB8fHww", applicantFullName: "Priya Sharma", currentJobPosition: "Data Scientist", currentOrganization: "Hireance", location: "Austin, USA", experience: 4, skills: ["React Native", "Swift", "Kotlin", "Firebase"], salaryRange: "15 - 20", lastUpdate: 6, linkedIn: "https://linkedin.com/in/priya", github: "https://github.com/priya", twitter: "https://twitter.com/priya", gmail: "priya@example.com", status: "Shortlisted", matchScore: 89 },
  { applicantId: "app-2006", profilePicture: "https://media.istockphoto.com/id/2203067311/photo/young-female-teacher-with-curly-hair-in-classroom-smiling-at-camera-with-arms-crossed.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWdN0e5FstxltxR6bWZ2y0BGH3hAmRb8iMYU-S9Q6uM=", applicantFullName: "David Kim", currentJobPosition: "Mobile Developer", currentOrganization: "Apple", location: "San Francisco, USA", experience: 7, skills: ["React", "TypeScript", "GraphQL", "Redux"], salaryRange: "16 - 21", lastUpdate: 7, linkedIn: "https://linkedin.com/in/david", github: "https://github.com/david", twitter: "https://twitter.com/david", gmail: "david@example.com", status: "Interviewed", matchScore: 92 },
  { applicantId: "app-2007", profilePicture: "https://media.istockphoto.com/id/2203067311/photo/young-female-teacher-with-curly-hair-in-classroom-smiling-at-camera-with-arms-crossed.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWdN0e5FstxltxR6bWZ2y0BGH3hAmRb8iMYU-S9Q6uM=", applicantFullName: "Alex Mercer", currentJobPosition: "Security Engineer", currentOrganization: "Meta", location: "Remote", experience: 8, skills: ["Pentesting", "C++", "Networking", "Linux"], salaryRange: "20 - 30", lastUpdate: 8, linkedIn: "https://linkedin.com/in/alex", github: "https://github.com/alex", twitter: "https://twitter.com/alex", gmail: "alex@example.com", status: "New", matchScore: 78 },
  { applicantId: "app-2008", profilePicture: "https://media.istockphoto.com/id/2203067311/photo/young-female-teacher-with-curly-hair-in-classroom-smiling-at-camera-with-arms-crossed.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWdN0e5FstxltxR6bWZ2y0BGH3hAmRb8iMYU-S9Q6uM=", applicantFullName: "Jane Doe", currentJobPosition: "Project Manager", currentOrganization: "Slack", location: "London, UK", experience: 5, skills: ["Agile", "Scrum", "Jira", "Strategy"], salaryRange: "14 - 18", lastUpdate: 1, linkedIn: "https://linkedin.com/in/jane", github: "https://github.com/jane", twitter: "https://twitter.com/jane", gmail: "jane@example.com", status: "Rejected", matchScore: 45 },
  { applicantId: "app-2009", profilePicture: "https://media.istockphoto.com/id/2203067311/photo/young-female-teacher-with-curly-hair-in-classroom-smiling-at-camera-with-arms-crossed.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWdN0e5FstxltxR6bWZ2y0BGH3hAmRb8iMYU-S9Q6uM=", applicantFullName: "Bob Smith", currentJobPosition: "QA Automation", currentOrganization: "Twitter", location: "New York, USA", experience: 4, skills: ["Selenium", "Python", "Cypress", "Appium"], salaryRange: "12 - 16", lastUpdate: 2, linkedIn: "https://linkedin.com/in/bob", github: "https://github.com/bob", twitter: "https://twitter.com/bob", gmail: "bob@example.com", status: "New", matchScore: 71 },
  { applicantId: "app-2010", profilePicture: "https://media.istockphoto.com/id/2203067311/photo/young-female-teacher-with-curly-hair-in-classroom-smiling-at-camera-with-arms-crossed.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWdN0e5FstxltxR6bWZ2y0BGH3hAmRb8iMYU-S9Q6uM=", applicantFullName: "Alice Johnson", currentJobPosition: "Cloud Engineer", currentOrganization: "IBM", location: "Remote", experience: 6, skills: ["GCP", "Docker", "Go", "Terraform"], salaryRange: "18 - 24", lastUpdate: 3, linkedIn: "https://linkedin.com/in/alice", github: "https://github.com/alice", twitter: "https://twitter.com/alice", gmail: "alice@example.com", status: "Shortlisted", matchScore: 95 },
  { applicantId: "app-2011", profilePicture: "https://media.istockphoto.com/id/2203067311/photo/young-female-teacher-with-curly-hair-in-classroom-smiling-at-camera-with-arms-crossed.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWdN0e5FstxltxR6bWZ2y0BGH3hAmRb8iMYU-S9Q6uM=", applicantFullName: "Kevin Heart", currentJobPosition: "HR Lead", currentOrganization: "Disney", location: "Orlando, USA", experience: 9, skills: ["Hiring", "Culture", "Retention", "Strategy"], salaryRange: "15 - 22", lastUpdate: 4, linkedIn: "https://linkedin.com/in/kevin", github: "https://github.com/kevin", twitter: "https://twitter.com/kevin", gmail: "kevin@example.com", status: "Rejected", matchScore: 32 }
];
